<script
	src="<?php echo $this->baseUrl() ?>/js/scripts/revalida/index.js"></script>
<link
	href="<?php echo $this->baseUrl('css/horas-extras-diario/index.css') ?>"
	rel="stylesheet">
<link href="<?php echo $this->baseUrl('css/horas-extras/index.css') ?>"
	rel="stylesheet">
<div class="form-group has-feedback row">
	<label class="control-label col-sm-3" for="dt_referencia">Meses
		disponíveis:</label>
	<div class="col-sm-5">
		<select class="form-control row" name="dt_referencia"
			id="dtReferencia">
            <?php
            foreach ($this->mesesDisponiveis as $key => $value) {
                echo "<option>";
                echo $value['dt_referencia'];
                echo "</option>";
            }
            ?>
        </select>
	</div>
	<br /> <br /> <br />
</div>
<div id="loadmsg" class="well well-sm row" style="display: none;"></div>
<div id="meta" class="row">
	<div class="col-xs-3">Funcionários:</div>
	<div id="totalCedes" class=" orange col-xs-3">---</div>
	<div class="col-xs-3">Total CEDESBR:</div>
	<div id="totalGeral" class=" orange col-xs-3">---</div>
</div>
<div id="porEmpregado">
	<br /> <br />
	<div class="table-responsive">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Matrícula</th>
					<th>Empregado</th>
					<th>Coordenação</th>
					<th>Horas 284</th>
					<th>Horas 285</th>
					<th>Valor 284</th>
					<th>Valor 285</th>
					<th>Total Horas</th>
					<th>Total Valor</th>
				</tr>
			</thead>
			<tbody id="tbodyEmpregado">
			</tbody>
		</table>
	</div>
</div>
