<script
	src="<?php echo $this->baseUrl() ?>/js/scripts/horas-extras/graficos.js"></script>
<script
	src="<?php echo $this->baseUrl() ?>/js/scripts/horas-extras/index.js"></script>
<link
	href="<?php echo $this->baseUrl('css/horas-extras-diario/index.css') ?>"
	rel="stylesheet">
<link href="<?php echo $this->baseUrl('css/horas-extras/index.css') ?>"
	rel="stylesheet">
<div class="form-group has-feedback row">
	<label class="control-label col-sm-3" for="dt_referencia">Meses
		disponíveis:</label>
	<div class="col-sm-5">
		<select class="form-control row" name="dt_referencia"
			id="dtReferencia">
            <?php
            foreach ($this->mesesDisponiveis as $key => $value) {
                echo "<option>";
                echo $value['dt_referencia'];
                echo "</option>";
            }
            ?>
        </select>
	</div>
	<br /> <br /> <br />
</div>
<div id="loadmsg" class="well well-sm row" style="display: none;"></div>


<ul class="nav nav-tabs row">
	<li role="presentation" class="active" id="tabGeralCEDESBR"><a href="#"
		onclick="clickGeralCEDESBR()">Geral - CEDESBR</a></li>
	<li role="presentation" id="tabPorCoordenacao"><a href="#"
		onclick="clickPorCoordenacao()">Por Coordenação</a></li>
	<li role="presentation" id="tabPorEquipe"><a href="#"
		onclick="clickPorEquipe()">Por Equipe</a></li>
	<li role="presentation" id="tabPorEmpregado"><a href="#"
		onclick="clickPorEmpregado()">Por Empregado</a></li>
	<li role="presentation" id="tabExportacao"><a href="#"
		onclick="clickExportacao()">Exportar Dados</a></li>
	<li role="presentation" id="tabExportacaoAnual"><a href="#"
		onclick="clickExportacaoAnual()">Exportar Dados Anuais</a></li>
</ul>
<div id="GeralCEDESBR" class="row">
	<h2 class="sub-header row" id="titulo"></h2>
	<div class="row">
		<div id="containerGraphGeral" class="col-xs-12"></div>
	</div>
	<div class="row">
		<hr />
		<h3>Valores por mês</h3>
		<hr />
	</div>
	<div class="row">
		<div class="col-xs-6" id="containerTempo"></div>
		<div class="col-xs-6" id="containerValor"></div>
	</div>
	<div class="row">
		<div class="col-xs-12" id="containerMes"></div>
	</div>
</div>

<div id="porCoordenacao" style="display: none;">
	<div id="meta" class="row">
		<div class="col-xs-3">Total Horas:</div>
		<div id="totalHorasCEDES" class=" orange col-xs-3">---</div>
		<div class="col-xs-3">Total Valor:</div>
		<div id="totalValorCEDES" class=" orange col-xs-3">---</div>
	</div>
	<div class="table-responsive">
		<table class="table table-striped  table-bordered">
			<thead>
				<tr>
					<th>Coordenação</th>
					<th>285</th>
					<th>296</th>
					<th>302</th>
					<th>Demais Projetos</th>
					<th>285 (R$)</th>
					<th>296 (R$)</th>
					<th>302 (R$)</th>
					<th>Demais Projetos (R$)</th>
					<th>Saldo a Compensar</th>
					<th>Saldo a Compensar (R$)</th>
					<th>Total</th>
					<th>Total (R$)</th>
				</tr>
			</thead>
			<tbody id="tbodyCoordenacao">
			</tbody>
		</table>
	</div>
</div>

<div id="porEquipe" style="display: none;">
	<h2 class="sub-header" id="titulo">
    Totalização por Equipe - <?php echo $this->ultimoMesDisponivel ?>
    </h2>
	<div id="areaGrafico"></div>
	<div class="table-responsive">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Equipe</th>
					<th>285</th>
					<th>296</th>
					<th>302</th>
					<th>Demais Projetos</th>
					<th>285 (R$)</th>
					<th>296 (R$)</th>
					<th>302 (R$)</th>
					<th>Demais Projetos (R$)</th>
					<th>Saldo a Compensar</th>
					<th>Saldo a Compensar (R$)</th>
					<th>Total</th>
					<th>Total (R$)</th>
				</tr>
			</thead>
			<tbody id="tbodyEquipe">
			</tbody>
		</table>
	</div>
</div>

<div id="porEmpregado" style="display: none;">
	<h2 class="sub-header" id="titulo">Totalização por Empregado - <?php echo $this->ultimoMesDisponivel ?></h2>
	<br /> <br />
	<div class="form-group has-feedback">
		<label class="control-label col-sm-3" for="area">Filtrar por equipe:</label>
		<div class="col-sm-9">
			<select class="form-control" name="area" id="area">
				<option selected="selected" value="0">Selecione...</option>
			</select>
		</div>
	</div>
	<br /> <br />
	<div class="table-responsive">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Empregado</th>
					<th>285</th>
					<th>296</th>
					<th>302</th>
					<th>Demais Projetos</th>
					<th>285 (R$)</th>
					<th>296 (R$)</th>
					<th>302 (R$)</th>
					<th>Demais Projetos (R$)</th>
					<th>Saldo a Compensar</th>
					<th>Saldo a Compensar (R$)</th>
					<th>Total</th>
					<th>Total (R$)</th>
				</tr>
			</thead>
			<tbody id="tbodyEmpregado">
			</tbody>
		</table>
	</div>
</div>

<div id="exportacao" style="display: none;">
	<h2 class="sub-header" id="titulo">Exportação de Dados</h2>
	<span style="color: #337AB7;"> Selecione os campos que deseja exportar
		ou <a href="#" id="selecionaTodos"><b>clique aqui</b></a> para
		selecionar todos
	</span> <br /> <br />
	<form name="exportacao" id="formExportacao"
		action="<?php echo $this->baseUrl(); ?>/horas-extras/exportacao"
		method="post">
		<input type="hidden" name="dt_referencia" id="dtReferenciaExportacao"
			value="" />
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="no_funcionario">Nome
				do Empregado</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]"
				value="no_matricula_caixa">Matrícula</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="no_matr_func">User
				ID</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="no_sigla_coord">Sigla
				da Coordenação</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="de_coord">Nome
				da Coordenação</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="no_sigla_area">Sigla
				da Equipe</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="de_area">Nome da
				Equipe</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="nu_he_pg_285">285</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="nu_he_pg_296">296</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="nu_he_pg_302">302</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]"
				value="nu_he_pg_demais_proj">Demais Projetos</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]"
				value="nu_valor_he_pg_285">285 (R$)</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]"
				value="nu_valor_he_pg_296">296 (R$)</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]"
				value="nu_valor_he_pg_302">302 (R$)</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]"
				value="nu_valor_he_pg_demais_proj">Demais Projetos (R$)</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="nu_he_comp_284">Saldo
				a Compensar</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]"
				value="nu_valor_he_comp_284">Saldo a Compensar (R$)</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]" value="nu_total_he">Total</label>
		</div>
		<div class="checkbox">
			<label><input type="checkbox" name="campos[]"
				value="nu_valor_total_he">Total (R$)</label>
		</div>
	</form>
	<br />
	<button type="button" class="btn btn-primary" id="btnExportar">Exportar
		Dados</button>
</div>

<div id="exportacaoAnual" style="display: none;">
	<h2 class="sub-header" id="titulo">Exportação de Dados Anual</h2>
	<form name="exportacaoAnual" id="formExportacaoAnual"
		action="<?php echo $this->baseUrl(); ?>/horas-extras/exportacao-anual"
		method="post">
		<div class="form-group has-feedback">
			<label class="control-label col-sm-2" for="ano">Selecione o ano:</label>
			<div class="col-sm-3">
				<select class="form-control" name="ano" id="ano">
                    <?php
                    foreach ($this->anosDisponiveis as $key => $value) {
                        echo "<option>";
                        echo $value['ano'];
                        echo "</option>";
                    }
                    ?>
                </select>
			</div>
		</div>
	</form>
	<br /> <br />
	<button type="button" class="btn btn-primary" id="btnExportarAnual">Exportar
		Dados</button>
</div>
