<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="http://www.caixa.gov.br" target="blank"><img
				src="<?php echo $this->baseUrl('img/logo_caixa.png') ?>" /></a> <a
				class="navbar-brand"
				href="http://desenvolvimentobr.coredf.caixa/portal/" target="blank">CN
				Desenvolvimento de TI Brasília</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">

			</ul>
		</div>
	</div>
</nav>