<div id="modalAlteraSenha" class="modal fade">

	<div class="modal-dialog">

		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title">Alteração de Senha</h4>
			</div>

			<div class="well well-sm" style="display: none;"
				id="alertaAlteraSenha"></div>

			<div class="modal-body">

				<form class="navbar-form navbar-left" role="search">
					<div class="form-group">
						<input type="password" class="form-control" name="nova_senha"
							placeholder="Nova Senha">
					</div>
					<div class="form-group">
						<input type="password" class="form-control" name="nova_senha2"
							placeholder="Confirme Nova Senha">
					</div>
					<button type="button" class="btn btn-primary" id="btnAlteraSenha">Alterar
						Senha</button>
				</form>

				<br />

				<p class="text-warning">
					<small></small>
				</p>
			</div>

			<br /> <br />

		</div>

	</div>

</div>

