<script
	src="<?php echo $this->baseUrl(); ?>/js/scripts/organograma/backbone-min.js"></script>
<script
	src="<?php echo $this->baseUrl(); ?>/js/scripts/organograma/lodash.min.js"></script>
<script
	src="<?php echo $this->baseUrl(); ?>/js/scripts/organograma/joint.js"></script>
<script
	src="<?php echo $this->baseUrl(); ?>/js/scripts/organograma/joint.shapes.org.js"></script>
<script
	src="<?php echo $this->baseUrl(); ?>/js/scripts/organograma/organograma.js"></script>
<script
	src="<?php echo $this->baseUrl(); ?>/js/scripts/organograma/joint.ui.tooltip.js"></script>

<!-- <link rel="stylesheet" type="text/css" href="/js/scripts/organograma/joint.ui.tooltip.css" /> -->
<link href="<?php echo $this->baseUrl('css/organograma/joint.css') ?>"
	rel="stylesheet">
<link
	href="<?php echo $this->baseUrl('css/organograma/joint.ui.tooltip.css') ?>"
	rel="stylesheet">
<div id="loadmsg" class="well well-sm row" style="display: none;"></div>
<div id="Graficos" class="row" style="height: 1000px; width: 1000px;">
	<button type="button" class="btn  pull-left btnBack" id="btnBackOrgan">Voltar</button>
	<br /> <br />
</div>
