<h4>Bem vindo ao Painel de Gestão CedesBR</h4>

<br />

Autenticação inválida. Tente novamente.

<br />
<br />

<form class="navbar-form navbar-left" role="search" method="post"
	action="<?php echo $this->baseUrl(); ?>/login/login">

	<input type="hidden" name="nu_funcionario" />

	<div class="form-group">
		<input type="text" class="form-control" name="usuario"
			placeholder="User ID">
	</div>
	<div class="form-group">
		<input type="password" class="form-control" name="senha"
			placeholder="Senha">
	</div>
	<button type="submit" class="btn btn-primary">Entrar</button>
</form>
