<script
	src="<?php echo $this->baseUrl(); ?>/js/scripts/sobreaviso/index.js"></script>
<link href="<?php echo $this->baseUrl('css/sobreaviso/index.css') ?>"
	rel="stylesheet">

<div class="form-group has-feedback">
	<label class="control-label col-sm-3" for="dt_referencia">Datas
		indisponíveis:</label>
	<div class="col-sm-5">
		<select class="form-control" name="dt_referencia" id="dtReferencia">
            <?php
            foreach ($this->DatasDisponiveis as $key => $value) {
                echo "<option>";
                echo $value['dt_referencia'];
                echo "</option>";
            }
            ?>
        </select>
	</div>
</div>
<br />
<br />
<br />
<div id="loadmsg" class="well well-sm" style="display: none;"></div>
<ul class="nav nav-tabs">
	<li role="presentation" class="active" id="tabPorCoordenacao"><a
		href="#" onclick="clickPorCoordenacao()">Por Coordenacao</a></li>
	<li role="presentation" id="tabPorEmpregado"><a href="#"
		onclick="clickPorEmpregado()">Por Empregado</a></li>
</ul>

<div id="porCoordenacao">
	<div id="meta" class="row">
		<div class="col-xs-3">Mês:</div>
		<div id="MesSobreaviso" class="col-xs-3">---</div>
		<div class="col-xs-3">Teto por Coordenação:</div>
		<div id="MetaSobreaviso" class="col-xs-3">---</div>
	</div>

	<div class="table-responsive">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Coordenação</th>
					<th>Minutos(Previsão)</th>
					<th>Executado</th>
				</tr>
			</thead>
			<tbody id="tbodySobreavisoCoord"></tbody>
		</table>
	</div>
</div>

<div id="porEmpregado" style="display: none;">

	<div class="form-group has-feedback">
		<label class="control-label col-sm-3" for="area">Filtrar por
			Coordenação:</label>
		<div class="col-sm-9">
			<select class="form-control" name="area" id="coords">
				<option selected="selected" value="0">Selecione...</option>
			</select>
		</div>
	</div>

	<br /> <br /> <br />

	<div class="col-md-12 text-center">
		<button type="button" class="btn btn-primary "
			onclick="hideTypeBleh()">Previsto e não executado</button>
		<button type="button" class="btn btn-success "
			onclick="hideTypeYahoo()">Previsto e executado</button>
		<button type="button" class="btn btn-danger "
			onclick="hideTypeSobad()">Executado e não previsto</button>
	</div>


	<br /> <br /> <br />


	<div class="table-responsive">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Coordenação</th>
					<th>Nome</th>
					<th>Minutos</th>
				</tr>
			</thead>
			<tbody id="tbodySobreavisoEmpregado"></tbody>
		</table>
	</div>
</div>
