<script
	src="<?php echo $this->baseUrl() ?>/js/scripts/admin/cadastrar.js"></script>
<span id="respostaValidacao"></span>
<p>
<form enctype="multipart/form-data" class="navbar-form navbar-left"
	role="form" method="post"
	action="<?php echo $this->baseUrl(); ?>/admin/adicionar-usuario">
	<input type="hidden" name="nu_funcionario" />
	<div class="form-group">
		<input type="text" class="form-control" name="matricula"
			placeholder="User ID">
	</div>
	<div class="form-group" style="display: none;">
		<input type="password" class="form-control" name="senha"
			placeholder="Senha">
	</div>
	<button type="button" class="btn btn-primary" id="btnValidar">Validar</button>
	<button type="submit" class="btn btn-primary" id="btnCadastrar"
		style="display: none;">Cadastrar</button>
</form>
<br />
<br />
<br />
<br />
</p>
